version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: chiss_oracle
    ports:
      - "6500:5432"
    volumes:
      - chiss_oracleDB:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
volumes:
  chiss_oracleDB: